<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGhfrSC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGhfrSC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGhfrSC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGhfrSC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEGhfrSC\App_KernelDevDebugContainer([
    'container.build_hash' => 'EGhfrSC',
    'container.build_id' => 'd077fd26',
    'container.build_time' => 1607565556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGhfrSC');
