<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUyvMD8c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUyvMD8c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUyvMD8c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUyvMD8c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUyvMD8c\App_KernelDevDebugContainer([
    'container.build_hash' => 'UyvMD8c',
    'container.build_id' => 'afb15eae',
    'container.build_time' => 1607566359,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUyvMD8c');
