<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8uqeIhd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8uqeIhd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8uqeIhd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8uqeIhd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8uqeIhd\App_KernelDevDebugContainer([
    'container.build_hash' => '8uqeIhd',
    'container.build_id' => 'fded2128',
    'container.build_time' => 1607947248,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8uqeIhd');
