<?php

namespace Container8uqeIhd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z8U9OQZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z8U9OQZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z8U9OQZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projectRolesRepository' => ['privates', 'App\\Repository\\ProjectRolesRepository', 'getProjectRolesRepositoryService', true],
        ], [
            'projectRolesRepository' => 'App\\Repository\\ProjectRolesRepository',
        ]);
    }
}
