<?php

namespace Container8uqeIhd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BA9zviUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BA9zviU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BA9zviU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'spokenLanguagesRepository' => ['privates', 'App\\Repository\\SpokenLanguagesRepository', 'getSpokenLanguagesRepositoryService', true],
        ], [
            'spokenLanguagesRepository' => 'App\\Repository\\SpokenLanguagesRepository',
        ]);
    }
}
