<?php

namespace Container8uqeIhd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TWBFQtGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tWBFQtG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tWBFQtG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'careerSummary' => ['privates', '.errored..service_locator.tWBFQtG.App\\Entity\\CareerSummary', NULL, 'Cannot autowire service ".service_locator.tWBFQtG": it references class "App\\Entity\\CareerSummary" but no such service exists.'],
        ], [
            'careerSummary' => 'App\\Entity\\CareerSummary',
        ]);
    }
}
