<?php

namespace Container8uqeIhd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCareerSummaryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tWBFQtG.App\Entity\CareerSummary' shared service.
     *
     * @return \App\Entity\CareerSummary
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tWBFQtG": it references class "App\\Entity\\CareerSummary" but no such service exists.');
    }
}
