<?php

namespace Container8uqeIhd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguagesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LanguagesType' shared autowired service.
     *
     * @return \App\Form\LanguagesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LanguagesType.php';

        return $container->privates['App\\Form\\LanguagesType'] = new \App\Form\LanguagesType();
    }
}
