<?php

namespace Container8uqeIhd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpokenLanguagesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SpokenLanguagesType' shared autowired service.
     *
     * @return \App\Form\SpokenLanguagesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SpokenLanguagesType.php';

        return $container->privates['App\\Form\\SpokenLanguagesType'] = new \App\Form\SpokenLanguagesType();
    }
}
