<?php

namespace Container1vxGqx0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6EItiidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6EItiid' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6EItiid'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'spokenLanguage' => ['privates', '.errored..service_locator.6EItiid.App\\Entity\\SpokenLanguages', NULL, 'Cannot autowire service ".service_locator.6EItiid": it references class "App\\Entity\\SpokenLanguages" but no such service exists.'],
        ], [
            'spokenLanguage' => 'App\\Entity\\SpokenLanguages',
        ]);
    }
}
