<?php

namespace Container1vxGqx0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4GXXyqoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4GXXyqo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4GXXyqo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'skill' => ['privates', '.errored..service_locator.4GXXyqo.App\\Entity\\Skills', NULL, 'Cannot autowire service ".service_locator.4GXXyqo": it references class "App\\Entity\\Skills" but no such service exists.'],
        ], [
            'skill' => 'App\\Entity\\Skills',
        ]);
    }
}
