<?php

namespace Container1vxGqx0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ga9SxLSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ga9SxLS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ga9SxLS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personalDatum' => ['privates', '.errored..service_locator.ga9SxLS.App\\Entity\\PersonalData', NULL, 'Cannot autowire service ".service_locator.ga9SxLS": it references class "App\\Entity\\PersonalData" but no such service exists.'],
        ], [
            'personalDatum' => 'App\\Entity\\PersonalData',
        ]);
    }
}
