<?php

namespace Container1vxGqx0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEducationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8P6TCot.App\Entity\Education' shared service.
     *
     * @return \App\Entity\Education
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8P6TCot": it references class "App\\Entity\\Education" but no such service exists.');
    }
}
