<?php

namespace Container1vxGqx0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpokenLanguagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6EItiid.App\Entity\SpokenLanguages' shared service.
     *
     * @return \App\Entity\SpokenLanguages
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6EItiid": it references class "App\\Entity\\SpokenLanguages" but no such service exists.');
    }
}
