<?php

namespace ContainerEGhfrSC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8P6TCotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8P6TCot' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8P6TCot'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'education' => ['privates', '.errored..service_locator.8P6TCot.App\\Entity\\Education', NULL, 'Cannot autowire service ".service_locator.8P6TCot": it references class "App\\Entity\\Education" but no such service exists.'],
        ], [
            'education' => 'App\\Entity\\Education',
        ]);
    }
}
