<?php

namespace ContainerEGhfrSC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LFLtI47Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lFLtI47' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lFLtI47'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'language' => ['privates', '.errored..service_locator.lFLtI47.App\\Entity\\Languages', NULL, 'Cannot autowire service ".service_locator.lFLtI47": it references class "App\\Entity\\Languages" but no such service exists.'],
        ], [
            'language' => 'App\\Entity\\Languages',
        ]);
    }
}
