<?php

namespace ContainerEGhfrSC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectRolesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Jal.0g_.App\Entity\ProjectRoles' shared service.
     *
     * @return \App\Entity\ProjectRoles
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Jal.0g_": it references class "App\\Entity\\ProjectRoles" but no such service exists.');
    }
}
