<?php

namespace ContainerEGhfrSC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechnicalExperienceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PS_L3Df.App\Entity\TechnicalExperience' shared service.
     *
     * @return \App\Entity\TechnicalExperience
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PS_L3Df": it references class "App\\Entity\\TechnicalExperience" but no such service exists.');
    }
}
