<?php

namespace ContainerX2Ic4OU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEducationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EducationType' shared autowired service.
     *
     * @return \App\Form\EducationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EducationType.php';

        return $container->privates['App\\Form\\EducationType'] = new \App\Form\EducationType();
    }
}
