<?php

namespace ContainerX2Ic4OU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lFLtI47.App\Entity\Languages' shared service.
     *
     * @return \App\Entity\Languages
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lFLtI47": it references class "App\\Entity\\Languages" but no such service exists.');
    }
}
