<?php

namespace ContainerX2Ic4OU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonalDataService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ga9SxLS.App\Entity\PersonalData' shared service.
     *
     * @return \App\Entity\PersonalData
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ga9SxLS": it references class "App\\Entity\\PersonalData" but no such service exists.');
    }
}
